using SQLAZOR.Models;

namespace SQLAZOR.Services;

public static class Constant
{
    public const string GeneratedHeader =
   "// <auto-generated>\n" +
   "//   Generated by SQLAZOR from the live database schema.\n" +
   "//   Hand-edit freely — this file is not regenerated automatically.\n" +
   "// </auto-generated>\n\n";

    #region Lower First
    public static string LowerFirst(string s) => string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s[1..];
    #endregion

    #region Escape Xml Doc
    public static string EscapeXmlDoc(string text) =>
   text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    #endregion

    #region Qualified Table Name
    public static string QualifiedTableName(TableInfo table) =>
   table.Schema.Equals("dbo", StringComparison.OrdinalIgnoreCase)
       ? $"[{table.TableName}]"
       : $"[{table.Schema}].[{table.TableName}]";
    #endregion
}
