<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Layout\CuPopover.razor.cs" />
    <Compile Remove="Services\HtmlSanitizerService.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Components\Layout\CuPopover.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Components\Layout\CuPopover.razor.css" />
    <None Remove="Components\Layout\CuPopover.razor.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
  </ItemGroup>

</Project>
