using SQLAZOR.Models;
using System.Text;

namespace SQLAZOR.Services;

public class GenerateDocumentationService : IGenerateDocumentationService
{
    public List<GeneratedFile> GenerateDocumentation(
    DatabaseSchema schema,
    IEnumerable<string> selectedTableKeys,
    List<StoredProcedureDetail> proceduresIncluded,
    List<GeneratedFile> allGeneratedFiles,
    string applicationName,
    string rootNamespace,
    string dbContextName,
    bool includeCrudServices,
    bool includeApiEndpoints,
    bool includeHttpClientServices,
    bool includeBlazorPages,
    PageStyle pageStyle,
    bool useCleanArchitecture)
    {
        var selected = selectedTableKeys.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var tables = schema.Tables.Where(t => selected.Contains(t.FullyQualifiedName)).OrderBy(t => t.TableName).ToList();
        var relevantFks = schema.ForeignKeys
            .Where(fk => selected.Contains($"{fk.ParentSchema}.{fk.ParentTable}") && selected.Contains($"{fk.ReferencedSchema}.{fk.ReferencedTable}"))
            .ToList();

        var html = BuildDocumentationHtml(
            schema, tables, relevantFks, proceduresIncluded, allGeneratedFiles,
            applicationName, rootNamespace, dbContextName, includeCrudServices, includeApiEndpoints,
            includeHttpClientServices, includeBlazorPages, pageStyle, useCleanArchitecture);

        return [new GeneratedFile { RelativePath = "docs/index.html", Content = html }];
    }


    private static string BuildDocumentationHtml(
    DatabaseSchema schema,
    List<TableInfo> tables,
    List<ForeignKeyInfo> relevantFks,
    List<StoredProcedureDetail> procedures,
    List<GeneratedFile> allFiles,
    string applicationName,
    string rootNamespace,
    string dbContextName,
    bool includeCrudServices,
    bool includeApiEndpoints,
    bool includeHttpClientServices,
    bool includeBlazorPages,
    PageStyle pageStyle,
    bool useCleanArchitecture)
    {
        var hasProjectFiles = allFiles.Any(f => f.RelativePath.EndsWith(".csproj") || f.RelativePath.EndsWith(".sln"));
        var pageStyleName = pageStyle switch { PageStyle.MudBlazor => "MudBlazor", PageStyle.Tabler => "Tabler", _ => "Plain HTML" };

        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"UTF-8\" />");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />");
        sb.AppendLine($"<title>{Constant.HtmlEncode(applicationName)} \u2014 Documentation</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(DocumentationCss);
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<div class=\"doc-shell\">");

        // ---- sidebar ----
        sb.AppendLine("  <nav class=\"doc-sidebar\">");
        sb.AppendLine($"    <div class=\"doc-brand\">{Constant.HtmlEncode(applicationName)}</div>");
        sb.AppendLine($"    <div class=\"doc-meta\">Generated by SchemaForge<br/>{DateTime.Now:yyyy-MM-dd}</div>");
        sb.AppendLine("    <a href=\"#overview\">Overview</a>");
        sb.AppendLine("    <a href=\"#architecture\">Architecture</a>");
        sb.AppendLine($"    <a href=\"#entities\">Entities ({tables.Count})</a>");
        if (relevantFks.Count > 0) sb.AppendLine("    <a href=\"#relationships\">Relationships</a>");
        if (includeApiEndpoints) sb.AppendLine("    <a href=\"#endpoints\">API Endpoints</a>");
        if (procedures.Count > 0) sb.AppendLine("    <a href=\"#procedures\">Stored Procedures</a>");
        sb.AppendLine("    <a href=\"#structure\">Project Structure</a>");
        sb.AppendLine("    <a href=\"#getting-started\">Getting Started</a>");
        sb.AppendLine("  </nav>");

        sb.AppendLine("  <main class=\"doc-content\">");

        AppendOverviewSection(sb, schema, tables, procedures, applicationName, includeCrudServices,
            includeApiEndpoints, includeHttpClientServices, includeBlazorPages, pageStyleName, useCleanArchitecture);

        AppendArchitectureSection(sb, applicationName, rootNamespace, dbContextName, useCleanArchitecture,
            includeCrudServices, includeApiEndpoints, includeHttpClientServices, includeBlazorPages, pageStyleName);

        AppendEntitiesSection(sb, tables, relevantFks);

        if (relevantFks.Count > 0)
        {
            AppendRelationshipsSection(sb, relevantFks);
        }

        if (includeApiEndpoints)
        {
            AppendEndpointsSection(sb, tables);
        }

        if (procedures.Count > 0)
        {
            AppendProceduresSection(sb, procedures);
        }

        AppendStructureSection(sb, allFiles, applicationName, useCleanArchitecture);

        AppendGettingStartedSection(sb, applicationName, useCleanArchitecture, hasProjectFiles, includeCrudServices);

        sb.AppendLine("  </main>");
        sb.AppendLine("</div>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }
    private static void AppendOverviewSection(
       StringBuilder sb, DatabaseSchema schema, List<TableInfo> tables, List<StoredProcedureDetail> procedures,
       string applicationName, bool includeCrudServices, bool includeApiEndpoints, bool includeHttpClientServices,
       bool includeBlazorPages, string pageStyleName, bool useCleanArchitecture)
    {
        sb.AppendLine("    <section id=\"overview\">");
        sb.AppendLine("      <h1>" + Constant.HtmlEncode(applicationName) + "</h1>");
        sb.AppendLine($"      <p class=\"lead\">Reverse-engineered from the <code>{Constant.HtmlEncode(schema.DatabaseName)}</code> SQL Server database by SchemaForge.</p>");

        sb.AppendLine("      <div class=\"stat-row\">");
        sb.AppendLine($"        <div class=\"stat-box\"><div class=\"stat-num\">{tables.Count}</div><div class=\"stat-label\">Tables</div></div>");
        sb.AppendLine($"        <div class=\"stat-box\"><div class=\"stat-num\">{tables.Sum(t => t.Columns.Count)}</div><div class=\"stat-label\">Columns</div></div>");
        sb.AppendLine($"        <div class=\"stat-box\"><div class=\"stat-num\">{procedures.Count}</div><div class=\"stat-label\">Stored Procedures</div></div>");
        sb.AppendLine("      </div>");

        sb.AppendLine("      <h3>Included in this build</h3>");
        sb.AppendLine("      <div class=\"badge-row\">");
        sb.AppendLine("        <span class=\"badge\">EF Core</span>");
        if (includeCrudServices) sb.AppendLine("        <span class=\"badge\">Dapper + Mapster</span>");
        if (includeApiEndpoints) sb.AppendLine("        <span class=\"badge\">REST API</span>");
        if (includeHttpClientServices) sb.AppendLine("        <span class=\"badge\">HttpClient services</span>");
        if (includeBlazorPages) sb.AppendLine($"        <span class=\"badge\">Blazor UI \u2014 {Constant.HtmlEncode(pageStyleName)}</span>");
        if (useCleanArchitecture) sb.AppendLine("        <span class=\"badge badge-accent\">Clean Architecture</span>");
        sb.AppendLine("      </div>");
        sb.AppendLine("    </section>");
    }

    private static void AppendArchitectureSection(
        StringBuilder sb, string applicationName, string rootNamespace, string dbContextName, bool useCleanArchitecture,
        bool includeCrudServices, bool includeApiEndpoints, bool includeHttpClientServices, bool includeBlazorPages, string pageStyleName)
    {
        sb.AppendLine("    <section id=\"architecture\">");
        sb.AppendLine("      <h2>Architecture</h2>");

        if (useCleanArchitecture)
        {
            sb.AppendLine("      <p>Four projects, dependencies enforced by real project references:</p>");
            sb.AppendLine("      <table class=\"doc-table\">");
            sb.AppendLine("        <thead><tr><th>Project</th><th>Contains</th><th>Depends on</th></tr></thead>");
            sb.AppendLine("        <tbody>");
            sb.AppendLine($"          <tr><td><code>{Constant.HtmlEncode(applicationName)}.Domain</code></td><td>Entities</td><td>&mdash;</td></tr>");
            sb.AppendLine($"          <tr><td><code>{Constant.HtmlEncode(applicationName)}.Application</code></td><td>DTOs, ResponseResult&lt;T&gt;, service interfaces</td><td>Domain</td></tr>");
            sb.AppendLine($"          <tr><td><code>{Constant.HtmlEncode(applicationName)}.Infrastructure</code></td><td>EF Core, Dapper service implementations, stored-proc executors</td><td>Application</td></tr>");
            sb.AppendLine($"          <tr><td><code>{Constant.HtmlEncode(applicationName)}.Web</code></td><td>Controllers, Blazor pages, Program.cs</td><td>Infrastructure</td></tr>");
            sb.AppendLine("        </tbody>");
            sb.AppendLine("      </table>");
        }
        else
        {
            sb.AppendLine($"      <p>Single project, root namespace <code>{Constant.HtmlEncode(rootNamespace)}</code>:</p>");
            sb.AppendLine("      <table class=\"doc-table\">");
            sb.AppendLine("        <thead><tr><th>Folder</th><th>Contains</th></tr></thead>");
            sb.AppendLine("        <tbody>");
            sb.AppendLine("          <tr><td><code>Entities/</code></td><td>POCO classes</td></tr>");
            sb.AppendLine("          <tr><td><code>Configurations/</code></td><td>EF Core Fluent API mappings</td></tr>");
            if (includeCrudServices)
            {
                sb.AppendLine("          <tr><td><code>Dtos/</code></td><td>Read/Create/Update DTOs</td></tr>");
                sb.AppendLine("          <tr><td><code>Common/</code></td><td><code>ResponseResult&lt;T&gt;</code></td></tr>");
                sb.AppendLine("          <tr><td><code>Services/</code></td><td>Service interfaces + Dapper implementations</td></tr>");
            }
            if (includeApiEndpoints) sb.AppendLine("          <tr><td><code>Controllers/</code></td><td>REST API controllers</td></tr>");
            if (includeBlazorPages) sb.AppendLine("          <tr><td><code>Components/</code></td><td>Blazor pages + admin dashboard shell</td></tr>");
            sb.AppendLine("        </tbody>");
            sb.AppendLine("      </table>");
        }

        sb.AppendLine($"      <p>Database access is via EF Core (<code>{Constant.HtmlEncode(dbContextName)}</code>)");
        if (includeCrudServices)
        {
            sb.AppendLine("      for the schema/entities, and <strong>Dapper</strong> (hand-written SQL, mapped with <strong>Mapster</strong>) for CRUD operations.</p>");
        }
        else
        {
            sb.AppendLine("      only \u2014 no CRUD service layer was generated in this build.</p>");
        }

        if (includeHttpClientServices)
        {
            sb.AppendLine("      <p>Every service has <strong>two</strong> implementations sharing one interface: a Dapper-backed one and an HttpClient-backed one that calls the REST API \u2014 register whichever matches how this project is deployed.</p>");
        }

        sb.AppendLine("    </section>");
    }

    private static void AppendEntitiesSection(StringBuilder sb, List<TableInfo> tables, List<ForeignKeyInfo> relevantFks)
    {
        sb.AppendLine("    <section id=\"entities\">");
        sb.AppendLine("      <h2>Entities</h2>");

        foreach (var table in tables)
        {
            var outgoingCount = relevantFks.Count(fk => fk.ParentSchema == table.Schema && fk.ParentTable == table.TableName);
            var incomingCount = relevantFks.Count(fk => fk.ReferencedSchema == table.Schema && fk.ReferencedTable == table.TableName);

            sb.AppendLine("      <div class=\"entity-card\">");
            sb.AppendLine($"        <h3>{Constant.HtmlEncode(table.ClassName)} <span class=\"entity-source\">{Constant.HtmlEncode(table.Schema)}.{Constant.HtmlEncode(table.TableName)}</span></h3>");
            sb.AppendLine("        <table class=\"doc-table\">");
            sb.AppendLine("          <thead><tr><th>Column</th><th>Property</th><th>Type</th><th>Nullable</th><th></th></tr></thead>");
            sb.AppendLine("          <tbody>");
            foreach (var col in table.Columns.OrderBy(c => c.OrdinalPosition))
            {
                var badges = new List<string>();
                if (col.IsPrimaryKey) badges.Add("<span class=\"tag tag-pk\">PK</span>");
                if (col.IsIdentity) badges.Add("<span class=\"tag\">identity</span>");
                if (col.IsComputed) badges.Add("<span class=\"tag\">computed</span>");
                var fk = relevantFks.FirstOrDefault(f => f.ParentSchema == table.Schema && f.ParentTable == table.TableName && f.ParentColumn == col.ColumnName);
                if (fk is not null) badges.Add($"<span class=\"tag tag-fk\">FK \u2192 {Constant.HtmlEncode(fk.ReferencedTable)}</span>");

                sb.AppendLine("            <tr>");
                sb.AppendLine($"              <td><code>{Constant.HtmlEncode(col.ColumnName)}</code></td>");
                sb.AppendLine($"              <td>{Constant.HtmlEncode(col.PropertyName)}</td>");
                sb.AppendLine($"              <td><code>{Constant.HtmlEncode(col.SqlDataType)}</code></td>");
                sb.AppendLine($"              <td>{(col.IsNullable ? "yes" : "no")}</td>");
                sb.AppendLine($"              <td>{string.Join(" ", badges)}</td>");
                sb.AppendLine("            </tr>");
            }
            sb.AppendLine("          </tbody>");
            sb.AppendLine("        </table>");
            if (outgoingCount > 0 || incomingCount > 0)
            {
                sb.AppendLine($"        <p class=\"entity-rel-summary\">{outgoingCount} outgoing relationship(s), {incomingCount} incoming.</p>");
            }
            sb.AppendLine("      </div>");
        }

        sb.AppendLine("    </section>");
    }


    private static void AppendRelationshipsSection(StringBuilder sb, List<ForeignKeyInfo> relevantFks)
    {
        sb.AppendLine("    <section id=\"relationships\">");
        sb.AppendLine("      <h2>Relationships</h2>");
        sb.AppendLine("      <table class=\"doc-table\">");
        sb.AppendLine("        <thead><tr><th>From</th><th>To</th><th>Constraint</th><th>On delete</th></tr></thead>");
        sb.AppendLine("        <tbody>");
        foreach (var fk in relevantFks.OrderBy(f => f.ParentTable))
        {
            sb.AppendLine("          <tr>");
            sb.AppendLine($"            <td><code>{Constant.HtmlEncode(fk.ParentTable)}.{Constant.HtmlEncode(fk.ParentColumn)}</code></td>");
            sb.AppendLine($"            <td><code>{Constant.HtmlEncode(fk.ReferencedTable)}.{Constant.HtmlEncode(fk.ReferencedColumn)}</code></td>");
            sb.AppendLine($"            <td>{Constant.HtmlEncode(fk.ConstraintName)}</td>");
            sb.AppendLine($"            <td>{Constant.HtmlEncode(fk.DeleteAction)}</td>");
            sb.AppendLine("          </tr>");
        }
        sb.AppendLine("        </tbody>");
        sb.AppendLine("      </table>");
        sb.AppendLine("    </section>");
    }

    private static void AppendEndpointsSection(StringBuilder sb, List<TableInfo> tables)
    {
        sb.AppendLine("    <section id=\"endpoints\">");
        sb.AppendLine("      <h2>API Endpoints</h2>");

        foreach (var table in tables.Where(t => t.PrimaryKeyColumns.Count > 0 && !t.IsView))
        {
            var pluralRoute = NamingHelper.Pluralize(table.ClassName).ToLowerInvariant();
            var routeTemplate = Constant.BuildPkPathSegment(table);

            sb.AppendLine($"      <h4>{Constant.HtmlEncode(table.ClassName)}</h4>");
            sb.AppendLine("      <table class=\"doc-table endpoint-table\">");
            sb.AppendLine("        <tbody>");
            AppendEndpointRow(sb, "GET", $"/api/{pluralRoute}", "Get all");
            AppendEndpointRow(sb, "GET", $"/api/{pluralRoute}/{routeTemplate}", "Get by key");
            AppendEndpointRow(sb, "POST", $"/api/{pluralRoute}", "Create");
            AppendEndpointRow(sb, "PUT", $"/api/{pluralRoute}/{routeTemplate}", "Update");
            AppendEndpointRow(sb, "DELETE", $"/api/{pluralRoute}/{routeTemplate}", "Delete");
            sb.AppendLine("        </tbody>");
            sb.AppendLine("      </table>");
        }

        sb.AppendLine("    </section>");
    }
    

    private static void AppendEndpointRow(StringBuilder sb, string method, string route, string description)
    {
        var methodClass = method.ToLowerInvariant();
        sb.AppendLine("          <tr>");
        sb.AppendLine($"            <td><span class=\"http-method http-{methodClass}\">{method}</span></td>");
        sb.AppendLine($"            <td><code>{Constant.HtmlEncode(route)}</code></td>");
        sb.AppendLine($"            <td>{Constant.HtmlEncode(description)}</td>");
        sb.AppendLine("          </tr>");
    }

    private static void AppendProceduresSection(StringBuilder sb, List<StoredProcedureDetail> procedures)
    {
        sb.AppendLine("    <section id=\"procedures\">");
        sb.AppendLine("      <h2>Stored Procedures</h2>");

        foreach (var proc in procedures.OrderBy(p => p.Name))
        {
            sb.AppendLine($"      <div class=\"entity-card\">");
            sb.AppendLine($"        <h3>{Constant.HtmlEncode(proc.Name)} <span class=\"entity-source\">{Constant.HtmlEncode(proc.Schema)}.{Constant.HtmlEncode(proc.Name)}</span></h3>");

            if (proc.Parameters.Count > 0)
            {
                sb.AppendLine("        <p class=\"doc-subheading\">Parameters</p>");
                sb.AppendLine("        <table class=\"doc-table\">");
                sb.AppendLine("          <thead><tr><th>Name</th><th>Type</th><th>Direction</th></tr></thead>");
                sb.AppendLine("          <tbody>");
                foreach (var p in proc.Parameters.OrderBy(p => p.Ordinal))
                {
                    sb.AppendLine("            <tr>");
                    sb.AppendLine($"              <td><code>{Constant.HtmlEncode(p.ParameterName)}</code></td>");
                    sb.AppendLine($"              <td><code>{Constant.HtmlEncode(p.SqlDataType)}</code></td>");
                    sb.AppendLine($"              <td>{(p.IsOutput ? "OUTPUT" : "IN")}</td>");
                    sb.AppendLine("            </tr>");
                }
                sb.AppendLine("          </tbody>");
                sb.AppendLine("        </table>");
            }

            if (proc.CanDescribeResultSet && proc.ResultColumns.Count > 0)
            {
                sb.AppendLine("        <p class=\"doc-subheading\">Result columns</p>");
                sb.AppendLine("        <table class=\"doc-table\">");
                sb.AppendLine("          <thead><tr><th>Column</th><th>Type</th><th>Nullable</th></tr></thead>");
                sb.AppendLine("          <tbody>");
                foreach (var c in proc.ResultColumns.OrderBy(c => c.Ordinal))
                {
                    sb.AppendLine("            <tr>");
                    sb.AppendLine($"              <td><code>{Constant.HtmlEncode(c.ColumnName)}</code></td>");
                    sb.AppendLine($"              <td><code>{Constant.HtmlEncode(c.SqlDataType)}</code></td>");
                    sb.AppendLine($"              <td>{(c.IsNullable ? "yes" : "no")}</td>");
                    sb.AppendLine("            </tr>");
                }
                sb.AppendLine("          </tbody>");
                sb.AppendLine("        </table>");
            }
            else
            {
                sb.AppendLine("        <p class=\"muted-note\">Result set couldn't be auto-described \u2014 see the generated executor's comments for details.</p>");
            }

            sb.AppendLine("      </div>");
        }

        sb.AppendLine("    </section>");
    }

    private static void AppendStructureSection(StringBuilder sb, List<GeneratedFile> allFiles, string applicationName, bool useCleanArchitecture)
    {
        sb.AppendLine("    <section id=\"structure\">");
        sb.AppendLine("      <h2>Project Structure</h2>");
        sb.AppendLine($"      <p>{allFiles.Count} file(s) generated.</p>");
        sb.AppendLine("      <pre class=\"file-tree\">");
        sb.Append(Constant.HtmlEncode(BuildFileTreeText(allFiles.Select(f => f.RelativePath))));
        sb.AppendLine("</pre>");
        sb.AppendLine("    </section>");
    }

    private static string BuildFileTreeText(IEnumerable<string> relativePaths)
    {
        var root = new SortedDictionary<string, object>(StringComparer.OrdinalIgnoreCase);

        foreach (var path in relativePaths)
        {
            var parts = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
            var node = root;
            for (var i = 0; i < parts.Length; i++)
            {
                var isFile = i == parts.Length - 1;
                if (isFile)
                {
                    node[parts[i]] = true; // leaf marker
                }
                else
                {
                    if (!node.TryGetValue(parts[i], out var next) || next is not SortedDictionary<string, object> nextDict)
                    {
                        nextDict = new SortedDictionary<string, object>(StringComparer.OrdinalIgnoreCase);
                        node[parts[i]] = nextDict;
                    }
                    node = (SortedDictionary<string, object>)node[parts[i]];
                }
            }
        }

        var sb = new StringBuilder();
        RenderTreeLevel(sb, root, 0);
        return sb.ToString();

        static void RenderTreeLevel(StringBuilder sb, SortedDictionary<string, object> level, int depth)
        {
            var indent = new string(' ', depth * 2);
            foreach (var (name, value) in level)
            {
                if (value is SortedDictionary<string, object> childDict)
                {
                    sb.AppendLine($"{indent}{name}/");
                    RenderTreeLevel(sb, childDict, depth + 1);
                }
                else
                {
                    sb.AppendLine($"{indent}{name}");
                }
            }
        }
    }

    private static void AppendGettingStartedSection(StringBuilder sb, string applicationName, bool useCleanArchitecture, bool hasProjectFiles, bool includeCrudServices)
    {
        sb.AppendLine("    <section id=\"getting-started\">");
        sb.AppendLine("      <h2>Getting Started</h2>");

        if (!hasProjectFiles)
        {
            sb.AppendLine("      <p>This build didn't include the full project scaffold (no <code>.csproj</code>/<code>.sln</code>), so these files are");
            sb.AppendLine("      meant to be dropped into an existing project rather than run standalone. Add the packages listed below to that project.</p>");
        }
        else
        {
            sb.AppendLine("      <ol class=\"steps\">");
            sb.AppendLine("        <li>Unzip everything, keeping the folder structure as-is.</li>");
            sb.AppendLine("        <li>Open <code>appsettings.json</code> and confirm <code>ConnectionStrings:DefaultConnection</code> \u2014 move it to");
            sb.AppendLine("            user secrets or an environment variable before this leaves your machine.</li>");
            if (useCleanArchitecture)
            {
                sb.AppendLine($"        <li>Open <code>{Constant.HtmlEncode(applicationName)}.sln</code> (or run <code>dotnet restore</code> from that folder).</li>");
                sb.AppendLine($"        <li><code>dotnet run --project {Constant.HtmlEncode(applicationName)}.Web</code></li>");
            }
            else
            {
                sb.AppendLine($"        <li>Open <code>{Constant.HtmlEncode(applicationName)}.csproj</code> (or run <code>dotnet restore</code> from that folder).</li>");
                sb.AppendLine("        <li><code>dotnet run</code></li>");
            }
            sb.AppendLine("      </ol>");
        }

        sb.AppendLine("      <p class=\"doc-subheading\">Packages this project needs</p>");
        sb.AppendLine("      <ul class=\"pkg-list\">");
        sb.AppendLine("        <li><code>Microsoft.EntityFrameworkCore.SqlServer</code> + <code>.Design</code> \u2014 always</li>");
        if (includeCrudServices)
        {
            sb.AppendLine("        <li><code>Microsoft.Data.SqlClient</code>, <code>Dapper</code>, <code>Mapster</code> \u2014 CRUD services</li>");
        }
        sb.AppendLine("      </ul>");

        sb.AppendLine("    </section>");
    }

    private const string DocumentationCss = """
:root {
  --bg: #f7f8fa;
  --panel: #ffffff;
  --border: #e2e5eb;
  --text: #1f2430;
  --muted: #6b7280;
  --accent: #4f46e5;
  --accent-soft: #eef2ff;
  --sidebar-bg: #14161f;
  --sidebar-text: #a6acc2;
  --sidebar-text-active: #ffffff;
  --code-bg: #f1f2f6;
  font-family: "Segoe UI", -apple-system, BlinkMacSystemFont, sans-serif;
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--text); }
.doc-shell { display: flex; min-height: 100vh; }
.doc-sidebar {
  width: 230px; flex-shrink: 0; background: var(--sidebar-bg); color: var(--sidebar-text);
  padding: 24px 16px; position: sticky; top: 0; height: 100vh; overflow-y: auto;
}
.doc-brand { color: var(--sidebar-text-active); font-size: 17px; font-weight: 700; margin-bottom: 4px; }
.doc-meta { font-size: 11.5px; color: #6b7280; margin-bottom: 20px; line-height: 1.5; }
.doc-sidebar a {
  display: block; padding: 8px 10px; border-radius: 6px; color: var(--sidebar-text);
  text-decoration: none; font-size: 13.5px; margin-bottom: 2px;
}
.doc-sidebar a:hover { background: rgba(255,255,255,0.06); color: var(--sidebar-text-active); }
.doc-content { flex: 1; padding: 40px 48px; max-width: 980px; }
.doc-content section { margin-bottom: 56px; scroll-margin-top: 20px; }
h1 { font-size: 28px; margin: 0 0 8px; }
h2 { font-size: 20px; border-bottom: 1px solid var(--border); padding-bottom: 10px; margin-bottom: 18px; }
h3 { font-size: 16px; margin-bottom: 10px; }
h4 { font-size: 14px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.4px; margin: 20px 0 8px; }
.lead { color: var(--muted); font-size: 14.5px; }
code { background: var(--code-bg); padding: 1px 6px; border-radius: 4px; font-size: 12.5px; font-family: Consolas, monospace; }
.stat-row { display: flex; gap: 14px; margin: 20px 0; }
.stat-box { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 16px 22px; }
.stat-num { font-size: 24px; font-weight: 700; color: var(--accent); }
.stat-label { font-size: 12px; color: var(--muted); margin-top: 2px; }
.badge-row { display: flex; gap: 8px; flex-wrap: wrap; }
.badge {
  background: var(--accent-soft); color: var(--accent); border-radius: 100px; padding: 5px 14px;
  font-size: 12.5px; font-weight: 600;
}
.badge-accent { background: #1f2430; color: #fff; }
.doc-table { width: 100%; border-collapse: collapse; background: var(--panel); border: 1px solid var(--border); border-radius: 8px; overflow: hidden; margin-bottom: 12px; }
.doc-table th, .doc-table td { padding: 8px 12px; text-align: left; border-bottom: 1px solid var(--border); font-size: 13px; }
.doc-table th { background: #fafbfc; font-size: 11px; text-transform: uppercase; color: var(--muted); letter-spacing: 0.4px; }
.doc-table tbody tr:last-child td { border-bottom: none; }
.entity-card { background: var(--panel); border: 1px solid var(--border); border-radius: 10px; padding: 20px 22px; margin-bottom: 16px; }
.entity-source { font-size: 12px; color: var(--muted); font-weight: 400; font-family: Consolas, monospace; margin-left: 8px; }
.entity-rel-summary { font-size: 12.5px; color: var(--muted); margin: 6px 0 0; }
.doc-subheading { font-size: 12px; text-transform: uppercase; color: var(--muted); letter-spacing: 0.4px; margin: 14px 0 6px; }
.tag { display: inline-block; background: #eef0f4; color: var(--muted); font-size: 10.5px; padding: 2px 7px; border-radius: 100px; margin-right: 4px; }
.tag-pk { background: #fef3c7; color: #92400e; }
.tag-fk { background: #dbeafe; color: #1e40af; }
.http-method { display: inline-block; font-size: 11px; font-weight: 700; padding: 3px 9px; border-radius: 5px; color: #fff; width: 54px; text-align: center; }
.http-get { background: #16a34a; }
.http-post { background: #2563eb; }
.http-put { background: #ea580c; }
.http-delete { background: #dc2626; }
.endpoint-table td { font-size: 12.5px; }
.file-tree { background: #14161f; color: #d1d5e0; padding: 18px 22px; border-radius: 10px; font-size: 12.5px; line-height: 1.6; overflow-x: auto; }
.steps { padding-left: 20px; }
.steps li { margin-bottom: 8px; font-size: 13.5px; }
.pkg-list { padding-left: 20px; font-size: 13.5px; }
.muted-note { color: var(--muted); font-size: 12.5px; font-style: italic; }
""";
}
